language: node_js

node_js:
  - "stable"

before_script:
  - npm install -g gulp-cli bower
  - bower install
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
